name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  create_release:
    name: Create Release
    runs-on: windows-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x'
        channel: 'stable'
    
    - name: Get dependencies
      run: cd todolist_fe && flutter pub get

    - name: Build execution file
      run: cd todolist_fe && flutter build windows

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: todolist_fe/build/windows/x64/runner/Release/todolist_fe.exe
        asset_name: todolist_fe.exe
        asset_content_type: application/octet-stream
        token: ${{ secrets.GITHUB_TOKEN }}
    