name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Test Connection
      run: curl "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json" 

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x'
        channel: 'stable'
    
    - name: Change directory to root flutter app folder
      run: cd todolist_fe

    - name: Get dependencies
      run: flutter pub get

    - name: Build execution file
      run: flutter build windows
