name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x'
        channel: 'stable'
    
    - name: Get dependencies
      run: cd todolist_fe && flutter pub get

    - name: Build execution file
      run: cd todolist_fe && flutter build windows